SUBTITLE(Upcoming talks by Daniel)
<ul>
#if 1
#define TALKS
#endif

<li> October 6, 2026: <a href="https://www.netnod.se/netnod-tech-meeting-2026">Netnod Tech Meeting</a>. Stockholm, Sweden.
<li> October 21, 2026. <a href="https://www.techboras.se/aktuellt/boras-tech-day-2026/">Borås Tech Day 2026</a>, Borås, Sweden
<li> October 31, 2026. FOSSCOMM 2026. Athens, Greece. Online.
#ifdef FULLPAGE
<li> November 4-6, 2026: <a href="https://nsss.se/2026/conference-news/nsss-fall-26/">NSSS</a> Stockholm, Sweden
<li> November 12, 2026: <a href="https://secureai.se/">Secure AI</a>, Stockholm Sweden
<li> November 23, 2026: <a href="https://www.ncsc.se/sv/aktuellt/svensk-cyber-2026/">Svensk Cyber 2026</a>, Stockholm Sweden
<li> November 26–27 2026. <a href="https://wawtech.io/">WAWTech 2026</A>, Warsaw, Poland.
</ul>
<p>
 Look me up and say hi!
#else
</ul>
See <a href="/talks.html">more talks</a>
#endif

#ifndef TALKS
<p>
 No planned (public) talks! Suggestions?
#endif
