SUBTITLE(Upcoming talks by Daniel)
<ul>
#if 0
<li> January 15, 2015: HTTP/2 in Berlin
<li> March 17, 2015: HTTP/2 for TCP/IP Geeks Stockholm
<li> September 10, 2015: HTTP/2 for Truesec
<li> October 2nd, 2015: <a href="http://apacheconcore2015.sched.org/event/cd9545130a7be6011b87e04b204130ab">Apachecon, Budapest</a>
<li> October 6th 2015: <a href="http://gotocon.com/cph-2015/presentation/HTTP/2">GOTO Conference, Copenhagen</a>
<li> October 13th 2015: <a href="http://velocityconf.com/devops-web-performance-ny-2015/public/schedule/detail/43776">Velocity, New York</a>
<li> November 3rd 2015: <a href="http://oredev.org/2015/security-day">&Oslash;redev Security Day, Malm&ouml;</a>
<li> November 4th 2015: <a href="http://oredev.org/2015/schedule">&Oslash;redev, Malm&ouml;</a>
<li> November 12th 2015: <a href="http://owaspstockholm20151112.eventbrite.com/">HTTP/2</a> - OWASP event, Stockholm
<li> November 30 2015, HTTP/2 talk [closed event]
<li> January 27 2016, <a href="https://www.eventbrite.com/e/owasp-stockholm-20160127-tickets-20064260744">HTTP/2 talk</a> in English in Stockholm
<li> January 30 2016, <a href="https://fosdem.org/2016/schedule/event/an_http2_update/">An HTTP/2 Update</a> at FOSDEM, Belgium
<li> February 3 2016, sneaky non-public HTTP/2 talk
<li> April 12 2016, HTTP/2 at <a href="http://www.meetup.com/Google-Tech-Talk-Meetup/events/228253543/">Google Tech Talk</a>, Stockholm
<li> April 14 2016, HTTP/2 at <a href="http://sue2016.snow.nl/">SUE 2016</a>, in Geldermalsen, the Netherlands
<li> April 15 2016, HTTP/2 at <a href="http://sue2016.snow.nl/">SUE 2016</a>, in Geldermalsen, the Netherlands (yes again)
<li> May 19 2016, HTTP/2 at a private event in Stockholm
<li> May 26 2016, "Everyone everywhere runs this code" on <a href="http://foss-north.se/">foss-north</a>, G&ouml;teborg, Sweden
<li> June 2 2016, HTTP/2 at <a href="https://webrebels.org/">Web Rebels</a> in Oslo, Norway
<li> September 28 2016, at <a href="http://www.ipexponordic.com/Seminar-Planner/Speakers/Daniel-Stenberg/">IP EXPO Nordic</a> in Stockholm, Sweden
<li> October 12 2016, <a href="https://www.meetup.com/FOSS-Sthlm/events/234150288/">foss-sthlm #18</a> in Stockholm 
<li> November 1 2016, HTTPS for SVT in Stockholm
<li> November 22 2016, <a href="https://internetdagarna.se/program/hall-kontakten/#tls">Internetdagarna</a> in Stockholm, Sweden
<li> November 24 2016, <a href="https://www.meetup.com/Tech-Day-by-Init/events/233581997/">Techdays By Init</a> Stockholm, Sweden
<li> December 2 2016, [private] Stockholm, Sweden
<li> February 4 2017, on <a href="https://fosdem.org/2017/schedule/event/curl/">curl</a> and <a href="https://fosdem.org/2017/schedule/event/mozilla_http2_whats_next/">HTTP2</a> at <a href="https://fosdem.org/2017/">FOSDEM</a> Brussels
<li> March 18 2017, <a href="https://github.com/curl/curl/wiki/curl-meeting-2017">curl://up</a>. Nuremberg, Germany
<li> March 18 2017, <a href="https://github.com/curl/curl/wiki/curl-meeting-2017">curl://up</a>. Nuremberg, Germany
<li> April 5 2017: at <a href="https://www.netnod.se/netnod-events/netnod-spring-meeting-2017/">Netnod spring meeting</a>, Stockholm Sweden
<li> May 9 2017: at Mirado
<li> April 28 2017: <a href="http://beta.craft-conf.com/">Craft</a>. Budapest, Hungary
<li> May 24 2017: HTTP/2 and QUIC at SVT, Stockholm Sweden
<li> September 13, 2017. "Day of the programmer" Jönköping, Sweden.
<li> November 4, 2017. <a href="https://2017.devfest.cz/">DevFest CZ</a> Prague, Czechia.
<li> March 6, 2018. Mozilla Tech Briefing on "Web Transports" (video online)
<li> April 14 2018, curl up in Stockholm
<li> April 15 2018, curl up in Stockholm
<li> April 21, 2018. Vetenskapsfestivalen, Göteborg
<li> September 11 2018, "Dalarna". Web transport and curl
<li> October 10, 2018, <a href="https://www.meetup.com/evolve-technology/events/254437880/">Pre-standup #2</a>, Göteborg Sweden
<li> November 8 2018, Stockholm, <a href="https://techworld.event.idg.se/event/codenight/">Code Night</a>
 <li> December 6, 2018, Stockholm, SVT. <a href="/http3-explained/">HTTP/3</a>

<li> January 17 2019, Stockholm (private). On <a href="/http3-explained/">HTTP/3</a>
 <li> January 22 2019. Stockholm <a href="https://www.goto10.se/evenemang/http-3/">Goto 10</a> on <a href="/http3-explained/">HTTP/3</a>.
 <li> January 28 2019, <a href="https://www.meetup.com/FOSS-Sthlm/events/257619567/">FOSS-Sthlm #20</a>, Stockholm. "säker kod"
 <li> February 2 2019, <a href="https://fosdem.org/2019/">FOSDEM</a>, Brussels Belgium. <a href="https://fosdem.org/2019/schedule/event/dns_over_http/">DNS-over-HTTPS</a>
 <li> February 2 2019, FOSDEM, Brussels Belgium. <a href="https://fosdem.org/2019/schedule/event/http3/">HTTP/3</a> in the Mozilla devroom.
 <li> February 3 2019, FOSDEM, Brussels Belgium. I'll participate in <a href="https://fosdem.org/2019/schedule/event/dns_privacy_panel/">the DNS privacy panel</a>
<li> March 12, 2019. Stockholm (Skandia). HTTP/2 and HTTP/3.
<li> March 19, 2019. Stockholm (private). HTTP/3.
<li> March 29 2019, <a href="https://github.com/curl/curl-up/wiki/2019">Symposium on the Future of HTTP</a> in Prague, Czech Republic. DNS-over-HTTPS.
 <li> March 30 2019, curl up, Prague, Czech Republic. Several curl-related talks.
 <li> March 31 2019, curl up, Prague, Czech Republic. Several curl-related talks.
 <li> April 9 2019, <a href="http://foss-north.se/2019/">FOSS-North</a>, Gothenburg, Sweden. <a href="https://foss-north.se/2019/speakers-and-talks.html#dstenberg">Writing safe and secure code</a>
 <li> May 2, 2019. Stockholm. DNS-over-HTTPS
 <li> May 7, 2019. The <a href="https://jax.de/en/">JAX conference</a>, Mainz Germany. <a href="https://jax.de/software-architecture/http-3-is-coming/">HTTP/3</a>
 <li> May 10, 2019. Stockholm (Klarna).
 <li> June 22, 2019, online (the <a href="https://blog.invidelabs.com/git-commit-sutta/">Git Commit Sutta</a> event) about curl
 <li> September 6, 2019, <a href="https://2019.fullstackfest.com/">Full Stack Fest</a> Barcelona Spain. <a href="https://2019.fullstackfest.com/speakers/daniel-stenberg">HTTP/3 - HTTP over QUIC is the next generation</a>
 <li> October 10, 2019. Stockholm. Developer's Bay. HTTP/3
 <li> October 14, 2019, Stockholm. <a href="https://castor-software-days-2019.github.io/">CASTOR Software Days</a> <a href="https://castor-software-days-2019.github.io/daniel_stenberg">"curl, a hobby project that conquered the world"</a>
 <li> October 22, 2019, Stockholm. <a href="https://nordicapis.com/events/the-2019-platform-summit/">Platform Summit 2019</a> <a href="https://nordicapis.com/?post_type=sessions&p=10929">"just curl it"</a>
 <li> October 24, 2019, Stockholm. <a href="https://cs3sthlm.se/">CS3 Sthlm</a> <a href="https://cs3sthlm.se/program/presentations/daniel-stenberg/">"curl - the world's most used software component?"</a>
<li> October 30, 2019, Stockholm. Active Solution. "curl - a hobby project that conquered the world"
<li> November 1, 2019. Copenhagen, Denmark. <a href="https://ida.dk/arrangementer-og-kurser/konferencer/driving-it">Driving IT 2019</a>. "curl runs in all your devices"
<li> November 14, 2019. Umeå. OWASP North. <a href="https://www.meetup.com/OWASP-North-Sweden/events/265482245">"HTTP/3 is coming and how we came to this"</a>
<li> November 19, 2019, Copenhagen, Denmark. <a href="https://gotocph.com/">GOTO Copenhagen</a>. <a href="https://gotocph.com/2019/sessions/953">"HTTP/3 is next generation HTTP. Is it QUIC enough?"</a>
<li> November 25, 2019, Stockholm, Sweden. <a href="https://internetdagarna.se/english/">Internetdagarna</a> <a href="https://internetdagarna.se/program/php-wordpress-and-beyond/">"HTTP/3 over QUIC. All is new but still the same"</a>
<li> December 4, 2019. Stockholm, Sweden. Load Impact. HTTP/3.
<li> December 12, 2019. Stockholm, Sweden. <a href="https://github.com/bagder/foss-sthlm-web/wiki/meetup-21">FOSS-sthlm #21</a> "HTTP/3 in curl"
<li> January 14, 2020. Webinar. Why everyone uses curl and you should too!
<li> January 21 2020, Stockholm, Sweden. <a href="https://www.meetup.com/Stockholm-Video-Technology/events/267372482/">Stockholm Video Tech Meetup</a> "HTTP/3, QUIC and Streaming"
<li> February 1, 2020, Brussels, Belgium. <a href="https://fosdem.org/2020/">FOSDEM</a>. <a href="https://fosdem.org/2020/schedule/event/http3/">HTTP/3 for everyone"</a> (main track: Janson)
<li> <strike>March 26-27, 2020. The Netherlands. <a href="https://sue2020.sue.nl/">SUE 2020</a>.</strike> (<b>Postponed due to COVID-19</b>)
<li> March 31, 2020. Online. <a href="https://foss-north.se/2020/">FOSS-North</a>. <a href="https://foss-north.se/2020/speakers-and-talks.html#dstenberg">curl better</a> (<b>Online event due to COVID-19</b>)
<li> May 9-10, 2020. Online. <a href="https://github.com/curl/curl-up/wiki/2020">curl up 2020</a>. There were talks. (<b>Online event due to COVID-19</b>)
<li> June 22, 2020. Online. Keynote at <a href="https://networking.ifip.org/2020/workshops/fit-2020">FIT 2020</a>
<li> July 6-9, 2020. Online. <a href="https://devoops-moscow.ru/en/">DevOops</a> - Going all in on HTTP/3 and QUIC (<b>Online due to COVID-19</b>)
<li> August 5, 2020, curl webinar for Japanese market
<li> August 13, 2020: <a href="https://daniel.haxx.se/blog/2020/08/05/upcoming-webinar-curl-how-to-make-your-first-code-contribution/">curl: How to Make Your First Code Contribution</a> (webinar)
<li> August 25, 2020: "Security in curl development" (for http://scadahackers.com/)
<li> October 28-30, 2020. Berlin, Germany. <a href="https://gotober.com/">GOTO Berlin</a>.  (cancelled)
<li> October 20-24, 2020. <a href="https://nerdear.la/en/">nerdear.la</a> <a href="https://nerdear.la/session/defensive-programming-at-curl/">Secure Development in the cURL factory</a> (<b>Online event</b>)
<li> November 10-11, 2020. <a href="https://gotopia.eu/november-2020/sessions/1626/http-3-is-next-generation-http-is-it-quic-enough">GOTO Copenhagen</a>. (<b>Online event</b>)
<li> December 7-9, 2020. Tokyo, Japan. Mercari Gears.  (<b>Online event</b>)
<li> March 1-5, 2021. Online. <a href="https://www.embedded-world.de/en/programme?lectureId=lELSYlUa6vd8I9RUy43p">Curl is the Internet Data Transfer Engine</a> at <a href="https://www.embedded-world.de/en">embedded world Conference 2021 DIGITAL</a>
<li> April 19-21, 2021. Copenhagen, Denmark. <a href="https://gotocph.com/">GOTO Copenhagen</a>.
<li> June 17, 2021. NLUUG. <a href="https://www.nluug.nl/vEvents/20210617-curl.html">Curl runs on all your devices</a>
<li> June 17, 2021. webinar: common libcurl mistakes
<li> September 21, 2021. Prague, Czechia. WebExpo, <a href="https://www.webexpo.net/prague2021/talk/just-curl-it">"just curl it"</a>
<li> October 6, 2021. Online curl talk done for a private audience
<li> October 13, 2021. Stockholm, Sweden. <a href="https://www.netnod.se/netnod-events/netnod-tech-meeeting-2021-1">Netnod Tech Meeting</a>. "curl is everywhere" - I will be there PHYSICALLY!
<li> October 21, 2021. Online webinar: <a href="https://daniel.haxx.se/blog/2021/10/12/coming-webinar-getting-started-with-libcurl/">getting started with libcurl</a>
<li> November 4, 2021. Using libcurl and tiny-curl. For wolfSSL.
<li> November 16, 2021. The making of curl and what's next. For a private audience.
<li> November 18, 2021. Webinar: <a href="https://daniel.haxx.se/blog/2021/11/16/curl-release-webinar-featuring-post-quantum-curl/">post-quantum curl</a>

<li> December 14, 2021. Panel discussion. <a href="https://sentry.io/resources/the-future-of-open-source-is-it-sustainable/?utm_medium=partner&utm_source=curl&utm_campaign=event-open-source-2021">The Future of Open Source: Is It Sustainable?</a>

<li> January 11, 2022: URL confusion
<li> January 27, 2022: curl with rust at Rust Linz
<li> February 3, 2022: "safe code" for a Swedish TV broadcasting company
<li> February 10, 2022: "safe code" for M.....
<li> February 17, 2022: <a href="https://daniel.haxx.se/blog/2022/02/14/the-great-curl-roadmap-2022-webinar/">curl roadmap 2022 webinar</a>
<li> April 29, 2022. talked curl for (unnamed company)
<li> June 2, 2022. GitHub Twitter space
<li> October 13, 2022. On EuroRust.
<li> October 19, 2022. curl in Östersund
<li> November 10, 2022. Webinar. Getting started with libcurl.
<li> November 24, 2022. <a href="https://www.meetup.com/jforum-stockholm/events/289354203/">curl is everywhere</a> on jforum-stockholm meetup, Stockholm.
<li> March 15, 2023. For RedHat Security
<li> March 17, 2023. "how curl came to be" for hitta.se
<li> March 20, 2023. curl birthday party presentation
<li> March 23, 2023. <a href="https://us02web.zoom.us/webinar/register/1616774545098/WN_TW7GcvmeR8uERGLUka94rA">curl roadmap 2023 webinar</a>
<li> April 6, 2023. webinar: QUIQ and HTTP/3 with curl and wolfSSL
<li> April 18, 2023. Keynote at <a href="https://openforumeurope.org/event/oss-swedish-eu-presidency/">Open Source Driving the Digital Decade</a>
<li> May 3, 2023. On <a href="https://stockholmtechshow.se/">Stockholm Tech Show</a>
<li> May 4, 2023. talk for STIM
<li> May 11, 2023. At <a href="https://myconf.io/">myConf</a>, Landskrona, Sweden. "just curl it"
<li> May 25, 2023. At CAG Contactor.
<li> June 15, 2023. WebSocket with libcurl webinar.
<li> June 20, 2023. curl user survey 2023 presentation
<li> August 30 2023. <a href="https://elastx.confetti.events/tech-fika-curl-fritidsprojektet-som-tog-sig-till-mars">At elastx</a>, Stockholm
<li> August 31 2023, <a href="https://daniel.haxx.se/blog/2023/08/08/mastering-the-curl-command-line/">Mastering the curl command line</a> (online)
<li> September 14 2023. <a href="https://www.keyfactor.com/community-tech-meetup-23/">At Keyfactor</a>, Stockholm
<li> October 18, 2023 <a href="https://nordicapis.com/events/platform-summit-2023/">Platform Summit 2023</a>, Stockholm, Sweden
<li> November 9, 2023. <a href="https://www.pycon.se/">PyCon Stockholm</a>, Sweden
<li> November 10, 2023. <a href="https://oredev.org/">Øredev</a>, Malmö
<li> November 16 2023: <a href="https://daniel.haxx.se/blog/2023/11/01/mastering-libcurl/">mastering libcurl</a>, part one
<li> November 20 2023: <a href="https://daniel.haxx.se/blog/2023/11/01/mastering-libcurl/">mastering libcurl</a> part two
#else
#define TALKS
<li> February 3-4 2024: FOSDEM talk being considered, but not decided yet
<li> May 22-23 2024: Stockholm Tech Show and Nordic Mobile
#ifdef FULLPAGE
<li> May 28-30 2024: (pending details)
</ul>
<p>
 Look me up and say hi!
#else
</ul>
See <a href="/talks.html">more talks</a>
#endif
#endif

#ifndef TALKS
<p>
 No planned (public) talks! Suggestions?
#endif