SUBTITLE(Upcoming talks by Daniel)
<ul>
#if 1
#define TALKS
#endif

<li> May 18, 2026: "AI code security" for Swedish cyber infra security people.
<li> May 21, 2026: <a
href="https://www.meetup.com/openinfra-user-group-sweden/events/313615139/">State
actors, sleeper agents and plain bugs. Curl security matters</a> Open Infra
Forum, Stockholm Sweden
<li> May 23-24, 2026: <a href="https://github.com/curl/curl-up/wiki/2026">curl up</a>, Prague, Czechia.
#ifdef FULLPAGE
<li> May 28, 2026: <a href="https://events.vtools.ieee.org/m/559728">Hiqh-Quality Chaos - on finding flaws in code with AI</a>. At KTH, Stockholm, Sweden.
<li> June 4, 2026: <a href="https://bsidesvilnius.lt/">BSides Vilnius</a>, Lithuania
<li> June 16-17, 2026: <a href="https://indico.neic.no/event/287/">BSides Ume 2026</a> keynote. Umeå, Sweden.
<li> September 15, 2026: Fastly Xcelerate, Stockholm Sweden.
<li> September 24, 2026: <a href="https://ndctechtown.com/">NDC TechTown</a>, Kongsberg, Norway: Three decades of curl.
<li> November 4-6, 2026: <a href="https://nsss.se/2026/conference-news/nsss-fall-26/">NSSS</a> Stockholm, Sweden
</ul>
<p>
 Look me up and say hi!
#else
</ul>
See <a href="/talks.html">more talks</a>
#endif

#ifndef TALKS
<p>
 No planned (public) talks! Suggestions?
#endif
