***************
*** 33,35 ****
  	@(dir=`pwd`;name=`basename $$dir`;echo Creates $$name.tar.gz; cd .. ; \
  	tar -cf $$name.tar `cat $$name/FILES | sed "s:^/:$$name/:g"` ; \
  	gzip $$name.tar ; chmod a+r $$name.tar.gz ; mv $$name.tar.gz $$name/)
--- 33,38 ----
  	@(dir=`pwd`;name=`basename $$dir`;echo Creates $$name.tar.gz; cd .. ; \
  	tar -cf $$name.tar `cat $$name/FILES | sed "s:^/:$$name/:g"` ; \
  	gzip $$name.tar ; chmod a+r $$name.tar.gz ; mv $$name.tar.gz $$name/)
+ 
+ clean:
+ 	rm *.o $(TARGET1).exe $(TARGET2).exe $(TARGET3).exe